
//=============================================================================
//                     JISON-LEX OPTIONS:

{
  lexerActionsUseYYLENG: '???',
  lexerActionsUseYYLINENO: '???',
  lexerActionsUseYYTEXT: '???',
  lexerActionsUseYYLOC: '???',
  lexerActionsUseParseError: '???',
  lexerActionsUseYYERROR: '???',
  lexerActionsUseLocationTracking: '???',
  lexerActionsUseMore: '???',
  lexerActionsUseUnput: '???',
  lexerActionsUseReject: '???',
  lexerActionsUseLess: '???',
  lexerActionsUseDisplayAPIs: '???',
  lexerActionsUseDescribeYYLOC: '???',
  lex_rule_dictionary: {
    rules: [
      {
        ast: {
          source: '[IDEM: srcCode]',
          augmentedSource: '[LINE-SHIFTED SOURCE]',
          ast: '[recast AST]',
          fault: false,
        },
        fault: false,
        srcCode: `// API Note:
        //
        // *all* \`yyerror()\` functions are expected to either return a token ID or throw an exception...
        //
        // Aside: by default, when your custom parseError() doesn't return a token ID, the token 'ERROR'
        // will be produced instead.
        //
        return yyerror(\`'${yytext[0]}' (${yytext.charCodeAt(0)}): illegal character at line ${yylineno}.\`)`,
        rule: '.',
      },
    ],
    moduleInclude: `// WARNING:
// The test rig DOES NOT include this 'epilogue' section into the generated lexer used for testing.  :-(
//
// Compare results with test 016, which 'fixes' this.
//
// DO NOTE that this is behaviour *specific* to the jison-lex test rig only! Both 016 and 017 should 
// behave the same when compiled to a full lexer using jison-gho/jison-lex.

lexer.yy = {
    parseError: function custom_parseError(str, hash, ExceptionClass) {
        if (0) console.error("invoking custom parseError:", {str});
        
        this.yytext = {
            text: this.yytext,
            message: str,
            // yyrulenumber      <-- that one is not accessible here.
        };
        return 666;
    }
}`,
    macros: {},
    startConditions: {},
    codeSections: [],
    importDecls: [],
    unknownDecls: [],
  },
  codeSections: [],
  importDecls: [],
  unknownDecls: [],
  options: {
    moduleType: 'commonjs',
    debug: false,
    enableDebugLogs: false,
    json: true,
    noMain: true,
    moduleMain: null,
    moduleMainImports: null,
    dumpSourceCodeOnFailure: false,
    throwErrorOnCompileFailure: true,
    doNotTestCompile: false,
    defaultModuleName: 'lexer',
    xregexp: false,
    lexerErrorsAreRecoverable: false,
    flex: false,
    backtrack_lexer: false,
    ranges: false,
    trackPosition: true,
    caseInsensitive: false,
    exportSourceCode: {
      enabled: false,
    },
    exportAST: false,
    prettyCfg: true,
  },
  conditions: {
    INITIAL: {
      rules: [
        0,
      ],
      inclusive: true,
    },
  },
  performAction: `function lexer__performAction(yy, yyrulenumber, YY_START) {
            const yy_ = this;

            
const YYSTATE = YY_START;
switch(yyrulenumber) {
case 0 : 
/*! Conditions:: INITIAL */ 
/*! Rule::       . */ 
 // API Note:
        //
        // *all* \`yy_.yyerror()\` functions are expected to either return a token ID or throw an exception...
        //
        // Aside: by default, when your custom parseError() doesn't return a token ID, the token 'ERROR'
        // will be produced instead.
        //
        return yy_.yyerror(\`'${yy_.yytext[0]}' (${yy_.yytext.charCodeAt(0)}): illegal character at line ${yy_.yylineno}.\`) 
break;
}
        }`,
  caseHelperInclude: `{

}`,
  rules: [
    {
      re: '/^(?:.)/',
      source: '^(?:.)',
      flags: '',
      xregexp: {
        captureNames: null,
        source: '^(?:.)',
        flags: '',
        isNative: true,
      },
    },
  ],
  macros: {},
  regular_rule_count: 1,
  simple_rule_count: 0,
  conditionStack: [
    'INITIAL',
  ],
  actionInclude: '',
  moduleInclude: `



// WARNING:
// The test rig DOES NOT include this 'epilogue' section into the generated lexer used for testing.  :-(
//
// Compare results with test 016, which 'fixes' this.
//
// DO NOTE that this is behaviour *specific* to the jison-lex test rig only! Both 016 and 017 should 
// behave the same when compiled to a full lexer using jison-gho/jison-lex.

lexer.yy = {
    parseError: function custom_parseError(str, hash, ExceptionClass) {
        if (0) console.error("invoking custom parseError:", {str});
        
        this.yytext = {
            text: this.yytext,
            message: str,
            // yyrulenumber      <-- that one is not accessible here.
        };
        return 666;
    }
}`,
  __in_rules_failure_analysis_mode__: false,
  is_custom_lexer: false,
}